repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
      args: [--unsafe]
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
      args: [--fix=lf]
- repo: local
  hooks:
    - id: black
      name: black
      entry: poetry run black .
      language: system
      types: [python]
    - id: isort
      name: isort
      entry: poetry run isort .
      language: system
      types: [python]
    - id: flake8
      name: flake8
      entry: poetry run flake8 .
      language: system
      types: [python]
